CREATE TABLE EMPLOYEE(
EMPID int NOT NULL PRIMARY KEY,
EMPFNAME VARCHAR(255),
EMPLNAME VARCHAR(255),
DEPARTMENT VARCHAR(255),
SALARY INT
);

INSERT INTO EMPLOYEE (EMPID,EMPFNAME,EMPLNAME,DEPARTMENT,SALARY) 
Select  1,'Shubham','Rajit','COMPUTER SCIENCE',50000 
UNION ALL  SELECT 2,'SHIVAM','SRIVASTAVA','COMMERCE',43000
UNION ALL  SELECT 3,'PRAVESH','DIXIT','COMMERCE',68000
UNION ALL  SELECT 4,'ROHIT','VERMA','COMPUTER SCIENCE',52000
UNION ALL  SELECT 5,'BRIJESH','KUMAR','MECHANICAL',80000

SELECT * FROM EMPLOYEE;

--HIGHEST THIRD SALARY
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;


SELECT * FROM EMPLOYEE ORDER BY SALARY DESC
SELECT * FROM EMPLOYEE E1 WHERE 3-1=(SELECT COUNT(DISTINCT SALARY) FROM EMPLOYEE E2 WHERE (E2.SALARY>E1.SALARY)); 



